[package]
name = "numbers"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "numbers"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdk = "0.0.115"
serde = "1"